apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30387   # Custom node port for access
  type: NodePort       # Change this from LoadBalancer to NodePort
