apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80            # Exposing on port 80
      targetPort: 8000     # Django app is running on port 8000
  type: LoadBalancer  