apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort          # Use LoadBalancer if on cloud (Azure AKS)
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000         # Service port
      targetPort: 8000   # Container port
      nodePort: 30007    # Port on the node (for NodePort type)
