apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80         # The port the service will expose
      targetPort: 8000  # The port where the Django app is running
  type: LoadBalancer
  loadBalancerIP: 52.224.216.56  # If you want to assign a specific IP, put it here
