apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80         # The port the service will expose
      targetPort: 8000  # The port where the Django app is running
      nodePort: 30387   # The port you will use to access the service externally
  type: NodePort      # Change to NodePort instead of LoadBalancer
