apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 externally
      targetPort: 8000  # Port your Django app listens to inside the container
      nodePort: 30080  # Port to expose on each node (you can customize this port)
  type: NodePort  # Change to NodePort
